// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr9FIGYaKPXW8o1O4uNImo74iS2ssNCTc',
    appId: '1:86132765250:web:3066b0f44db338a3ca33db',
    messagingSenderId: '86132765250',
    projectId: 'flutter-issue-tracking',
    authDomain: 'flutter-issue-tracking.firebaseapp.com',
    storageBucket: 'flutter-issue-tracking.appspot.com',
    measurementId: 'G-XW7YELME24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBasbNY36K76dvCGfeQjgd5v7USWZ59OpU',
    appId: '1:86132765250:android:bc8bbb887e20a77fca33db',
    messagingSenderId: '86132765250',
    projectId: 'flutter-issue-tracking',
    storageBucket: 'flutter-issue-tracking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkmH3DSCUwQO-d9QCClrUctv3TlPO22gk',
    appId: '1:86132765250:ios:d55aa7a5091d5cbcca33db',
    messagingSenderId: '86132765250',
    projectId: 'flutter-issue-tracking',
    storageBucket: 'flutter-issue-tracking.appspot.com',
    iosClientId: '86132765250-oh4065vr6oi2pmkqnvihle7ogp1db770.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterIssueTracker',
  );
}
